services:
  db:
    image: mysql:9.1.0
    container_name: orderManagment
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: managment
      MYSQL_USER: order-manager
      MYSQL_PASSWORD: mysecret
    volumes:
      - ./mysql:/var/lib/mysql